<?php

require_once __DIR__ . '/../src/Scaffolder.php';
require_once __DIR__ . '/../src/ExistingAppAugmenter.php';
require_once __DIR__ . '/../src/StaticAppImporter.php';

use Akirk\CreateWpApp\ExistingAppAugmenter;
use Akirk\CreateWpApp\Scaffolder;
use Akirk\CreateWpApp\StaticAppImporter;

$failures = [];

$test = static function( string $name, callable $callback ) use ( &$failures ): void {
    try {
        $callback();
        echo "PASS $name\n";
    } catch ( Throwable $e ) {
        $failures[] = "$name: " . $e->getMessage();
        echo "FAIL $name\n";
    }
};

$assert = static function( bool $condition, string $message ): void {
    if ( ! $condition ) {
        throw new RuntimeException( $message );
    }
};

$make_temp_dir = static function( string $prefix ): string {
    $dir = sys_get_temp_dir() . DIRECTORY_SEPARATOR . $prefix . '-' . bin2hex( random_bytes( 4 ) );
    if ( ! mkdir( $dir, 0777, true ) && ! is_dir( $dir ) ) {
        throw new RuntimeException( "Could not create temporary directory: $dir" );
    }

    return $dir;
};

$remove_dir = static function( string $dir ) use ( &$remove_dir ): void {
    if ( ! is_dir( $dir ) ) {
        return;
    }

    foreach ( scandir( $dir ) as $entry ) {
        if ( in_array( $entry, [ '.', '..' ], true ) ) {
            continue;
        }

        $path = $dir . DIRECTORY_SEPARATOR . $entry;
        if ( is_dir( $path ) && ! is_link( $path ) ) {
            $remove_dir( $path );
        } else {
            unlink( $path );
        }
    }

    rmdir( $dir );
};

$write_static_build = static function( string $target_dir, string $html = '<html><head></head><body><script src="/assets/app.js"></script></body></html>' ): void {
    mkdir( $target_dir . '/dist/assets', 0777, true );
    file_put_contents( $target_dir . '/dist/index.html', $html );
    file_put_contents( $target_dir . '/dist/assets/app.js', 'console.log("app");' );
};

$test( 'augment uses wp-app and preserves existing app directory', static function() use ( $assert, $make_temp_dir, $remove_dir, $write_static_build ): void {
    $root = $make_temp_dir( 'create-wp-app-test' );

    try {
        $target = $root . '/existing';
        mkdir( $target . '/app', 0777, true );
        file_put_contents( $target . '/app/page.jsx', 'export default function Page() {}' );
        $write_static_build( $target );

        ExistingAppAugmenter::augment( [ 'target_dir' => $target ] );

        $assert( is_file( $target . '/app/page.jsx' ), 'existing app/page.jsx was removed' );
        $assert( is_file( $target . '/wp-app/assets/app.js' ), 'static build was not imported to wp-app/' );
        $assert( is_file( $target . '/wp-app/' . StaticAppImporter::ASSET_MARKER_FILE ), 'asset marker was not written' );
    } finally {
        $remove_dir( $root );
    }
} );

$test( 'augment refuses to replace unmarked wp-app directory', static function() use ( $assert, $make_temp_dir, $remove_dir, $write_static_build ): void {
    $root = $make_temp_dir( 'create-wp-app-test' );

    try {
        $target = $root . '/existing';
        mkdir( $target . '/wp-app', 0777, true );
        file_put_contents( $target . '/wp-app/source.txt', 'do not delete' );
        $write_static_build( $target );

        try {
            ExistingAppAugmenter::augment( [ 'target_dir' => $target ] );
        } catch ( RuntimeException $e ) {
            $assert( strpos( $e->getMessage(), 'Refusing to replace existing directory' ) !== false, 'unexpected exception message' );
            $assert( file_get_contents( $target . '/wp-app/source.txt' ) === 'do not delete', 'unmarked wp-app directory was modified' );
            return;
        }

        throw new RuntimeException( 'augment did not reject an unmarked wp-app directory' );
    } finally {
        $remove_dir( $root );
    }
} );

$test( 'augment replaces marked generated asset directory', static function() use ( $assert, $make_temp_dir, $remove_dir, $write_static_build ): void {
    $root = $make_temp_dir( 'create-wp-app-test' );

    try {
        $target = $root . '/existing';
        mkdir( $target . '/wp-app', 0777, true );
        file_put_contents( $target . '/wp-app/' . StaticAppImporter::ASSET_MARKER_FILE, "Generated by create-wp-app.\n" );
        file_put_contents( $target . '/wp-app/old.txt', 'old build' );
        $write_static_build( $target );

        ExistingAppAugmenter::augment( [ 'target_dir' => $target ] );

        $assert( ! file_exists( $target . '/wp-app/old.txt' ), 'old generated asset file was not replaced' );
        $assert( is_file( $target . '/wp-app/assets/app.js' ), 'new asset file was not copied' );
    } finally {
        $remove_dir( $root );
    }
} );

$test( 'conversion rewrites assets but leaves anchor hrefs alone', static function() use ( $assert, $make_temp_dir, $remove_dir, $write_static_build ): void {
    $root = $make_temp_dir( 'create-wp-app-test' );

    try {
        $source = $root . '/source';
        $plugin = $root . '/plugin';
        $html = '<html><head><link rel="stylesheet" href="/assets/app.css"></head><body><a href="/about">About</a><script src="/assets/app.js"></script></body></html>';
        $write_static_build( $source, $html );
        file_put_contents( $source . '/dist/assets/app.css', 'body{}' );

        Scaffolder::create( [
            'slug' => 'demo-app',
            'plugin_name' => 'Demo App',
            'namespace' => 'DemoApp',
            'target_dir' => $plugin,
            'setup_type' => 'minimal',
            'source_app_dir' => $source,
        ] );

        $template = file_get_contents( $plugin . '/templates/index.php' );
        $assert( strpos( $template, '<a href="/about">About</a>' ) !== false, 'anchor href was rewritten' );
        $assert( strpos( $template, '$asset_url( \'assets/app.js\' )' ) !== false, 'script src was not rewritten' );
        $assert( strpos( $template, '$asset_url( \'assets/app.css\' )' ) !== false, 'stylesheet href was not rewritten' );
    } finally {
        $remove_dir( $root );
    }
} );

if ( $failures !== [] ) {
    echo "\n";
    foreach ( $failures as $failure ) {
        echo "$failure\n";
    }
    exit( 1 );
}
